#!/bin/bash

CMD_BASE="$(readlink -m $0)" || CMD_BASE="$0"; CMD_BASE="$(dirname $CMD_BASE)"
MBKP_CONF_FILE="$CMD_BASE/mbkp.conf"
. "$CMD_BASE/inc/configuration.inc.sh"
. "$CMD_BASE/inc/base.inc.sh"
. "$CMD_BASE/inc/top-level-functions.inc.sh"
. "$CMD_BASE/inc/misc.inc.sh"
. "$CMD_BASE/inc/mysql.inc.sh"
. "$CMD_BASE/inc/help.inc.sh"

(($#)) || usage

VERBOSE=0

main() {

  local params=()
  local cmd="$1"; shift

  while (($#)); do
    case "$1" in
      -v|--verbose)
        VERBOSE="$2"; shift
        ;;
      *)
        params+=("$1")
      ;;
    esac
    shift
  done

  case "$cmd" in
    b|backup)
      EXP_backup_modules "${params[@]}"
      ;;
    s|status)
      EXP_status "${params[@]}"
      ;;
    l|list)
      EXP_list "${params[@]}"
      ;;
    v|verify)
      EXP_verify "${params[@]}"
      ;;
    r|restore)
      EXP_restore "${params[@]}"
      ;;
    h|'help')
      EXP_help "${params[@]}"
      ;;
    *)
      echo "mbkp: unknown command '$cmd'"
      usage
      ;;
  esac

} # main

main "$@"

exit 0
