#!/bin/bash

CMD_BASE="$(readlink -m $0)" || CMD_BASE="$0"; CMD_BASE="$(dirname $CMD_BASE)"
MBKP_CONF_FILE="$CMD_BASE/mbkp.conf"
_INCLUDES=(
  configuration
  base
  top-level-functions
  misc
  mysql
  help
)
for item in "${_INCLUDES[@]}"; do . "$CMD_BASE/inc/$item.inc.sh"; done

(($#)) || usage

VERBOSE=0
_dry_run=0

main() {

  local params=()
  local cmd="$1"; shift

  while (($#)); do
    case "$1" in
      -v|--verbose)
        VERBOSE="$2"; shift
        ;;
      --dry-run)
        _dry_run=1
        ;;
      *)
        params+=("$1")
      ;;
    esac
    shift
  done

  case "$cmd" in
    b|backup)
      EXP_backup_modules "${params[@]}"
      ;;
    s|status)
      EXP_status "${params[@]}"
      ;;
    l|list)
      EXP_list "${params[@]}"
      ;;
    v|verify)
      EXP_verify "${params[@]}"
      ;;
    r|restore)
      EXP_restore "${params[@]}"
      ;;
    h|'help')
      EXP_help "${params[@]}"
      ;;
    c|'call')
      EXP_call "${params[@]}"
      ;;
    cb|'config-backup')
      EXP_config_backup "${params[@]}"
      ;;
    cr|'config-restore')
      EXP_config_restore "${params[@]}"
      ;;
    *)
      echo "mbkp: unknown command '$cmd'"
      usage
      ;;
  esac

} # main

main "$@"

exit 0
