#!/usr/bin/env bash
#
# mbkp - The modular backup tool
#
# Copyright 2010-2011 Elifarley Cruz <elifarley@gmail.com>
#
# This software may be used and distributed according to the terms of the
# GNU General Public License version 2 or any later version.

readonly _MBKP_VERSION='MBKP_VERSION'

CMD_BASE="$(readlink -f "$0")" || CMD_BASE="$0"; CMD_BASE="$(dirname "$CMD_BASE")"
eval readonly $(cat $CMD_BASE/inc/build.info)
MBKP_CONF_FILE="$CMD_BASE/mbkp.conf"
_INCLUDES='
  configuration
  base
  capabilities
  top-level-functions
  misc
  mysql
  help
'
for item in $_INCLUDES; do . "$CMD_BASE/inc/$item.inc.sh"; done

(($#)) || usage

_verbose=0
unset _dry_run
unset _force

main() {

  local cmd="$1"; shift

  local params=()
  while (($#)); do
    case "$1" in
      -v|--verbose)
        _verbose=1
        ;;
      --dry-run)
        _dry_run=1
        ;;
      --force)
        _force=1
        ;;
      *)
        params+=("$1")
      ;;
    esac
    shift
  done

  case "$cmd" in
    b|backup)
      EXP_backup_modules "${params[@]}"
      ;;
    s|status)
      EXP_status "${params[@]}"
      ;;
    l|list)
      EXP_list "${params[@]}"
      ;;
    v|verify)
      EXP_verify "${params[@]}"
      ;;
    r|restore)
      EXP_restore "${params[@]}"
      ;;
    'version'|--version)
      EXP_version "${params[@]}"
      ;;
    --help)
      usage "${params[@]}"
      ;;
    h|'help')
      EXP_help "${params[@]}"
      ;;
    c|'call')
      EXP_call "${params[@]}"
      ;;
    'log')
      EXP_log "${params[@]}"
      ;;
    cs|'cache-size')
      EXP_cache_size "${params[@]}"
      ;;
    cz|'cache-zap')
      EXP_cache_zap "${params[@]}"
      ;;
    cn|'config-new')
      EXP_config_new "${params[@]}"
      ;;
    cx|'config-export')
      EXP_config_export "${params[@]}"
      ;;
    ci|'config-import')
      EXP_config_import "${params[@]}"
      ;;
    ce|'config-edit')
      EXP_config_edit "${params[@]}"
      ;;
    dd|'db-dump')
      EXP_db_dump "${params[@]}"
      ;;
    di|'db-import')
      EXP_db_import "${params[@]}"
      ;;
    *)
      echo "mbkp: unknown command '$cmd'"
      usage
      ;;
  esac

} # main

main "$@"

exit 0
